Import serverError and code modification
A lot of errors: 
ERROR in src/app/session/session.service.ts:174:23 - error TS2339: 
Property 'form' does not exist on type 'SessionService'.

174     let toSend = this.form.value;
                          ~~~~
src/app/session/session.service.ts:181:40 - error TS2551: Property 
'session' does not exist on type 'SessionService'. Did you mean 
'sessionId'?

181         
this.router.navigateByUrl(this.session.getLoginRedirectionUrl());
                                           ~~~~~~~

  src/app/session/session.service.ts:76:3
    76   sessionId: string = '';
         ~~~~~~~~~
    'sessionId' is declared here.
src/app/session/session.service.ts:185:16 - error TS2339: Property 
'errors' does not exist on type 'SessionService'.

185           this.errors.emit(new ServerError(err, 'retrieving 
uninominal ballot'));